<?php
/**
 * Profit calculation engine.
 *
 * Empty by design at this stage: only documented method signatures. The
 * REST endpoint (ProfitLens_REST_Controller) currently builds the response
 * with example data directly; once this engine has logic, the controller
 * switches to calling get_summary() and the response contract doesn't
 * change — so wiring up the engine won't require touching the frontend.
 *
 * @package ProfitLens\Calculation
 */

defined( 'ABSPATH' ) || exit;

class ProfitLens_Profit_Engine {

	/**
	 * Active cost sources (FREE: only WooCommerce COGS; PRO adds more
	 * through this same contract, without touching the engine).
	 *
	 * @var ProfitLens_Cost_Source[]
	 */
	private $cost_sources;

	/**
	 * @param ProfitLens_Cost_Source[] $cost_sources
	 */
	public function __construct( array $cost_sources = array() ) {
		$this->cost_sources = $cost_sources;
	}

	/**
	 * Profit for a single order: revenue - product cost - gateway fee -
	 * shipping + refunds.
	 *
	 * Heads up when implementing this: WooCommerce can generate an
	 * automatic reconciliation WC_Order_Refund (reason "Order fully
	 * refunded.") as soon as an order's status changes to "refunded",
	 * without any real refund having been entered by hand — don't assume
	 * "1 refunded order = 1 trustworthy WC_Order_Refund". Always sum
	 * refunds via $order->get_total_refunded(), never by iterating and
	 * trusting there's at most one "real" refund. See CLAUDE.md, the
	 * WooCommerce-behavior section.
	 *
	 * @param WC_Order $order
	 * @return array{revenue:float,product_cost:float,gateway_fee:float,shipping:float,refunded:float,profit:float}
	 */
	public function calculate_order_profit( WC_Order $order ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Aggregate profit for a product over a date range: sum of units,
	 * revenue, cost, and margin % across every order that includes that
	 * product within the range.
	 *
	 * @param int               $product_id
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array{product_id:int,name:string,units:int,revenue:float,cost:float,profit:float,margin_pct:float}
	 */
	public function calculate_product_profit( $product_id, DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Total cost breakdown for the range by category (product cost,
	 * shipping, refunds, gateway fees), in the order and shape expected by
	 * `cost_breakdown` in the REST response. Each entry flags is_estimated
	 * based on what the corresponding cost source reports (see
	 * ProfitLens_Cost_Source::is_estimated()).
	 *
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array<int,array{key:string,label:string,amount:float,is_estimated:bool}>
	 */
	public function get_cost_breakdown( DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Cost coverage for the range, in two dimensions:
	 * - by catalog: % of sold products that have a cost set.
	 * - by revenue: % of the period's revenue generated by products with a
	 *   known cost. This is the figure that actually matters — a catalog
	 *   that's 93% covered can hide the fact that the best sellers'
	 *   costs are missing, and that's the scenario that makes the profit
	 *   number shown untrustworthy.
	 *
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array{products_with_cost:int,products_total:int,pct:float,revenue_covered_pct:float,revenue_uncovered:float}
	 */
	public function get_cost_coverage( DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Daily net profit series for the "Profit over time" chart.
	 *
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array<int,array{date:string,label:string,profit:float}>
	 */
	public function get_chart_series( DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Detects the most relevant insight for the range (for now: the
	 * product that generated the most negative profit). Returns null if
	 * there's no insight worth showing.
	 *
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array{type:string,message:string,product_id:int}|null
	 */
	public function get_insight( DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}

	/**
	 * Orchestrates everything above into the full shape returned by
	 * GET /profit-lens/v1/summary. This is the method
	 * ProfitLens_REST_Controller::get_summary() will call once the engine
	 * has real logic, instead of building the mock by hand.
	 *
	 * @param DateTimeInterface $after
	 * @param DateTimeInterface $before
	 * @return array
	 */
	public function get_summary( DateTimeInterface $after, DateTimeInterface $before ) {
		// TODO: not implemented yet.
		return null;
	}
}
